swagger: '2.0'
info:
  title: CICE API
  version: "1.0"
  description: |
    **Empleados API**

    Find source code of this API [here](https://mutua-repository)
# host: localhost:9080
#basePath: /empleados-api/v1
# schemes:
#   - http
#   - https
#consumes:
#  - application/json
#produces:
#  - application/json
#

securityDefinitions:
  basicAuth:
    type: basic
    description: HTTP Basic Authentication. Works over `HTTP` and `HTTPS`
    
paths:


       
  '/empleados':
    get:
      summary: Buscar empleados
      parameters:
        - name: cookie
          in: query
          description: Cookie para búsquedas paginadas
          type: string
          format: byte
          required: false
        - name: nombre
          in: query
          description: Nombre de empleado
          type: string
          required: false
        - name: apellidos
          in: query
          description: Apellidos de empleado
          type: string
          required: false
        - name: empresa
          in: query
          description: Empresa del empleado
          type: string
          required: false
        - name: unidad
          in: query
          description: Unidad en la empresa del empleado
          type: string
          required: false
        - name: telefono
          in: query
          description: Teléfono de empleado
          type: string
          required: false
        - name: extension
          in: query
          description: Extensión telefónica
          type: string
          required: false
      responses:
        '200':
          description: Búsqueda de empleados
          headers:
            X-Mutua-Correlation-Id:
              type: string
          schema:
            $ref: '#/definitions/ResultadoBusquedaEmpleado'

  '/empleados/{idEmpleado}':
     put:
      summary: Modificar datos Empleado
      parameters:
        - name: idEmpleado
          description: Id de empleado
          type: string
          in: path
          required: true
        - name: ubicacion
          in: query
          description: Oficinas del Empleado
          type: string
          required: false
        - name: localidad
          in: query
          description: Localidad del Empleado
          type: string
          required: false
        - name: provincia
          in: query
          description: Provincia del Empleado
          type: string
          required: false  
        - name: estadoCivil
          in: query
          description: Estado civil del Empleado
          type: string
          required: false
        - name: telefono
          in: query
          description: Teléfono de Empleado
          type: string
          required: false
        - name: fechaDeNacimiento
          in: query
          description: Fecha de nacimiento
          type: string
          required: false 
        - name: numeroDeCuenta
          in: query
          description: numero de cuenta de Empleado
          type: string
          required: false  
      responses:
        '200':
          description: Modificar datos Empleado ok 
          headers:
            X-Mutua-Correlation-Id:
              type: string      
     get:
      summary: Detalle de empleado
      parameters:
        - name: idEmpleado
          description: Id de empleado
          type: string
          in: path
          required: true
      responses:
        '200':
          description: Detalle de empleado
          headers:
            X-Mutua-Correlation-Id:
              type: string
          schema:
            $ref: '#/definitions/DetalleEmpleado'
  
  '/empleados/usuario/{usuario}':
    get:
      summary: Detalle de empleado
      parameters:
        - name: usuario
          description: Usuario de Mutua
          type: string
          in: path
          required: true
      responses:
        200:
          description: Detalle de empleado
          headers:
            X-Mutua-Correlation-Id:
              type: string
          schema:
            $ref: '#/definitions/DetalleEmpleado'
        400: 
          description: Bad Request
          headers:
            X-Mutua-Correlation-Id:
              type: string 
        500: 
          description: Error del servidor
          headers:
            X-Mutua-Correlation-Id:
              type: string      
            
  '/empleados/{idEmpleado}/preguntas':
    post:
      summary: Hacer una pregunta
      description: Hacer una pregunta
      parameters:
        - name: idEmpleado
          description: Id de empleado
          type: string
          in: path
          required: true
        - name: Pregunta
          description: Texto de la pregunta
          in: body
          schema:
            $ref: '#/definitions/Pregunta'
          required: true
      responses:
        200:
          description: Pregunta creada
          headers:
            X-Mutua-Correlation-Id:
              type: string

    
definitions:

  
  Empleado:
    type: object
    properties:
      id:
        type: string
      nombre:
        type: string
      apellidos:
        type: string
      avatar:
        type: string
        format: byte
      empresa:
        type: string
      unidad:
        type: string
      telefono:
        type: string
      extension:
        type: string
      email:
        type: string
        
  ResultadoBusquedaEmpleado:
    type: object
    properties:
      empleados:
        type: array
        items:
          $ref: "#/definitions/Empleado"
      cookie:
        type: string
        format: byte
     
  DetalleEmpleado:
    type: object
    allOf: 
      - $ref: "#/definitions/Empleado"
      - properties:
          codigoQR:
            type: string
            format: byte
          dni:
            type: string
          fechaNacimiento:
            type: string
            format: date
          estadoCivil:
            type: string  
          ubicacion:
            type: string
          localidad:
            type: string
          provincia:
            type: string
          logoempresa:
            type: string
          numeroDeHijos:
            type: number
          cuentaBancaria:
            type: string
  
 
          
  Pregunta:
    type: object
    properties:
      texto:
        description: Texto de la pregunta
        type: string
      tipoPregunta:
        type: string
        enum:
          - nomina
          - seguroSalud
     
 